In [3]:
import numpy as np


def givens_rotation(a, b):
    """
    计算 Givens 旋转矩阵的 cos 和 sin
    """
    if b == 0:
        c = 1
        s = 0
    else:
        r = np.hypot(a, b)  # sqrt(a^2 + b^2) 更稳定
        c = a / r
        s = b / r
    return c, s


def qr_decomposition_givens(A):
    """
    使用 Givens Rotation 实现矩阵的 QR 分解
    """
    m, n = A.shape
    Q = np.eye(m)
    R = A.copy()

    for j in range(n):  # 遍历列
        for i in range(m - 1, j, -1):  # 从底部向上消去
            c, s = givens_rotation(R[i - 1, j], R[i, j])

            # 构造 Givens 旋转矩阵
            G = np.eye(m)
            G[i - 1, i - 1] = c
            G[i, i] = c
            G[i - 1, i] = s
            G[i, i - 1] = -s

            # 更新 R 和 Q
            R = G @ R  # 应用旋转到 R
            Q = Q @ G.T  # 累积旋转到 Q.T

    return Q, R


# 示例
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])

Q, R = qr_decomposition_givens(A)

print("Q:")
print(Q)
print("R:")
print(R)

# 验证结果
print("Reconstructed A:")
print(Q @ R)

Q:
[[ 0.85714286 -0.39428571  0.33142857]
 [ 0.42857143  0.90285714 -0.03428571]
 [-0.28571429  0.17142857  0.94285714]]
R:
[[ 1.40000000e+01  2.10000000e+01 -1.40000000e+01]
 [-5.54027784e-16  1.75000000e+02 -7.00000000e+01]
 [ 4.65704514e-16  0.00000000e+00 -3.50000000e+01]]
Reconstructed A:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]


In [2]:
Q.shape

(5, 5)

In [12]:
Q, R = np.linalg.qr(A, mode="complete")

In [13]:
Q

array([[-0.85714286,  0.39428571,  0.33142857],
       [-0.42857143, -0.90285714, -0.03428571],
       [ 0.28571429, -0.17142857,  0.94285714]])

In [14]:
R

array([[ -14.,  -21.,   14.],
       [   0., -175.,   70.],
       [   0.,    0.,  -35.]])

In [2]:
Q.shape

(5, 5)

In [3]:
R.shape

(5, 3)