In [7]:
import numpy as np

In [8]:
def rsvd(A, rank, power_iterations=3):
    """
    Perform Randomized Singular Value Decomposition (RSVD).

    Parameters:
        A (np.ndarray): Input matrix.
        rank (int): Target rank for the approximation.
        power_iterations (int): Number of power iterations to enhance accuracy.

    Returns:
        u (np.ndarray): Left singular vectors.
        s (np.ndarray): Singular values.
        v (np.ndarray): Right singular vectors (transposed).
    """
    # Step 1: Generate a random matrix Omega
    n_rows, n_cols = A.shape
    Omega = np.random.randn(n_cols, rank)

    # Step 2: Perform power iteration
    Y = A @ Omega
    for _ in range(power_iterations):
        Y = A @ (A.T @ Y)

    # Step 3: Compute orthogonal matrix Q
    Q, _ = np.linalg.qr(Y)

    # Step 4: Project A onto the low-dimensional subspace
    B = Q.T @ A

    # Step 5: Compute SVD on the smaller matrix B
    u_tilde, s, v = np.linalg.svd(B, full_matrices=False)

    # Step 6: Recover the left singular vectors of A
    u = Q @ u_tilde

    return u, s, v

In [9]:
%%time
n = 2000
rank = 10
A = np.random.uniform(-1, 1, (n, n))

CPU times: user 17.9 ms, sys: 5.45 ms, total: 23.3 ms
Wall time: 47.4 ms


In [10]:
%%time
# Perform RSVD
rsvd(A, rank, power_iterations=2)

CPU times: user 11.8 ms, sys: 5.4 ms, total: 17.2 ms
Wall time: 15.3 ms


(array([[-0.00340463, -0.03255558,  0.0177377 , ..., -0.01664312,
          0.04387635, -0.00857284],
        [-0.03450108, -0.00328702,  0.01233636, ..., -0.00090779,
         -0.01046093, -0.00104875],
        [ 0.0431147 ,  0.00214874, -0.01520448, ...,  0.03134384,
         -0.01012907, -0.01933917],
        ...,
        [ 0.0021264 , -0.00382396,  0.02984609, ...,  0.01629427,
         -0.03951842, -0.02039664],
        [-0.0050246 ,  0.02489211,  0.02797375, ...,  0.00071844,
          0.01992515,  0.01321685],
        [ 0.04729232, -0.04303146,  0.01486049, ..., -0.04560733,
          0.04119548, -0.00946987]], shape=(2000, 10)),
 array([46.93737988, 46.85922237, 46.32673338, 46.11643754, 45.81164462,
        45.66982261, 45.44335841, 45.01352828, 44.40465493, 44.13649874]),
 array([[ 0.01264425,  0.00601113,  0.0073467 , ..., -0.01861615,
         -0.00239363,  0.06054813],
        [ 0.01700457,  0.00870304, -0.04158599, ...,  0.01825259,
         -0.02665541,  0.00728988],
   

In [11]:
%%time
np.linalg.svd(A, full_matrices=False)

CPU times: user 4.09 s, sys: 329 ms, total: 4.42 s
Wall time: 1.85 s


SVDResult(U=array([[ 6.39317996e-03, -1.50531191e-02, -1.02701446e-02, ...,
         2.50464737e-02, -1.04273442e-03,  2.09698635e-02],
       [-2.85850388e-04, -2.11000634e-02,  2.96836503e-02, ...,
        -1.70153496e-02, -3.40770532e-02,  2.37567494e-02],
       [ 1.50117656e-02,  4.90769886e-03,  3.14488420e-02, ...,
        -2.48556234e-03, -1.05159338e-02, -3.84307816e-03],
       ...,
       [ 3.13845383e-03,  6.49527544e-02, -5.37599625e-03, ...,
        -7.55573297e-03,  4.61554624e-02, -2.65855252e-02],
       [-5.71943118e-05,  2.04061130e-03, -5.03050587e-02, ...,
        -5.27107561e-02,  6.84814475e-05,  6.31948429e-03],
       [-1.30865975e-02, -1.31863933e-02,  1.79083176e-02, ...,
         2.63175874e-02, -2.66086819e-02, -7.22634737e-03]],
      shape=(2000, 2000)), S=array([5.13603950e+01, 5.11787409e+01, 5.10912295e+01, ...,
       2.98218420e-02, 2.37447453e-02, 7.11455375e-03], shape=(2000,)), Vh=array([[ 0.01449884,  0.00727484,  0.00472147, ..., -0.00599509,
  

In [14]:
import numpy as np

# 创建与 C++ 示例中相同的矩阵
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=float)

# 我们只想要前 rank 个奇异值和奇异向量
rank = 2

# 使用 numpy.linalg.svd 计算完整的 SVD
# full_matrices=False 会返回 "economy" 尺度的 U 和 Vt，使得 U.shape = (m, n), Vt.shape = (n, n)
U, s, Vt = np.linalg.svd(A, full_matrices=False)

# 提取前 rank 个奇异值与奇异向量
s_k = s[:rank]
U_k = U[:, :rank]  # 取前 rank 列
V_k = Vt[:rank, :].T  # Vt 是 V 的转置，所以这里转置回来以获得 V 矩阵

print("Singular values:\n", s_k, "\n")
print("U:\n", U_k, "\n")
print("V:\n", V_k, "\n")

Singular values:
 [25.46240744  1.29066168] 

U:
 [[-0.14087668 -0.82471435]
 [-0.34394629 -0.42626394]
 [-0.54701591 -0.02781353]
 [-0.75008553  0.37063688]] 

V:
 [[-0.50453315  0.76077568]
 [-0.5745157   0.05714052]
 [-0.64449826 -0.64649464]] 

