In [1]:
import numpy as np

In [2]:
def rsvd(A, rank, power_iterations=3):
    """
    Perform Randomized Singular Value Decomposition (RSVD).

    Parameters:
        A (np.ndarray): Input matrix.
        rank (int): Target rank for the approximation.
        power_iterations (int): Number of power iterations to enhance accuracy.

    Returns:
        u (np.ndarray): Left singular vectors.
        s (np.ndarray): Singular values.
        v (np.ndarray): Right singular vectors (transposed).
    """
    # Step 1: Generate a random matrix Omega
    n_rows, n_cols = A.shape
    Omega = np.random.randn(n_cols, rank)

    # Step 2: Perform power iteration
    Y = A @ Omega
    for _ in range(power_iterations):
        Y = A @ (A.T @ Y)

    # Step 3: Compute orthogonal matrix Q
    Q, _ = np.linalg.qr(Y)

    # Step 4: Project A onto the low-dimensional subspace
    B = Q.T @ A

    # Step 5: Compute SVD on the smaller matrix B
    u_tilde, s, v = np.linalg.svd(B, full_matrices=False)

    # Step 6: Recover the left singular vectors of A
    u = Q @ u_tilde

    return u, s, v

In [11]:
%%time
n = 2000
rank = 10
A = np.random.uniform(-1, 1, (n, n))

CPU times: user 17.7 ms, sys: 3.72 ms, total: 21.4 ms
Wall time: 56.9 ms


In [16]:
%%time
# Perform RSVD
rsvd(A, rank, power_iterations=2)

CPU times: user 11.6 ms, sys: 2.71 ms, total: 14.3 ms
Wall time: 19.8 ms


(array([[-1.10605546e-02,  1.42448081e-02,  3.83463371e-02, ...,
          1.27411354e-02, -1.74332625e-03,  8.56950927e-03],
        [ 1.36769268e-02,  1.33381980e-02, -1.34353911e-03, ...,
          8.04447884e-03, -2.69976756e-02,  2.46240834e-02],
        [-6.35430778e-03, -6.22866380e-02,  2.14555699e-02, ...,
         -9.72888526e-03,  1.68872333e-02, -1.11423762e-02],
        ...,
        [-1.56734623e-02, -8.31055372e-03,  1.28127283e-03, ...,
          3.37653757e-03,  1.08089693e-02,  1.97495927e-03],
        [ 1.19705849e-02,  4.70279425e-03,  2.28371382e-02, ...,
          1.44262499e-02, -3.54577168e-02,  2.97744251e-02],
        [ 2.34366115e-03,  5.85963934e-02,  1.23482535e-02, ...,
         -9.74680518e-05, -5.32026580e-03,  4.43669610e-02]],
       shape=(2000, 10)),
 array([47.23787869, 47.05933591, 46.76227337, 46.13301437, 45.9429272 ,
        45.68382409, 45.1771949 , 45.07089787, 44.65436737, 44.51386657]),
 array([[-0.00041385,  0.00710033,  0.00450039, ..., -0.

In [ ]:
%%time
np.linalg.svd(A, full_matrices=False)

CPU times: user 4.2 s, sys: 298 ms, total: 4.5 s
Wall time: 1.71 s
